version: "3.8"
services:
  bank-account:
    image: humbertobonadiman/bank-account:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-account
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/bank_account?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "sua_senha_aqui",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jackson.default-property-inclusion" : "NON_NULL",
        "spring.jackson.serialization.fail-on-empty-beans" : "false"
      }'
    networks:
      - bank-account-net
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - bank-account-net
    environment:
      - MYSQL_ROOT_PASSWORD=sua_senha_aqui
      - MYSQL_DATABASE=bank-account
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306
networks:
  bank-account-net:
     driver: bridge
volumes:
  db:
