name: Continuos Integration with GitHub

on:
  push:
    branches: [ "main" ]

jobs:
  Evaluator:
    runs-on: ubuntu-latest
    name: Evaluator
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
         java-version: '11'
         distribution: 'adopt'

      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Run Tests
      - name: Run Tests
        working-directory: .
        run: mvn -B test

  Application:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
      
        - name: Docker Login
          uses: docker/login-action@v2.0.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Setup Java JDK
          uses: actions/setup-java@v3.4.1
          with:
           java-version: '11'
           distribution: 'adopt'

        - name: Bank Account Container Jar
          working-directory: .
          run: mvn spring-boot:build-image -DskipTests

        - name: Docker Compose Build
          working-directory: .
          run: docker-compose build

        - name: Build and push Docker images
          run: |
            docker tag ${{ secrets.DOCKER_USERNAME }}/bank-account:1.0.0 ${{ secrets.DOCKER_USERNAME }}/bank-account:${{github.run_id}}
            docker tag ${{ secrets.DOCKER_USERNAME }}/bank-account:1.0.0 ${{ secrets.DOCKER_USERNAME }}/bank-account:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/bank-account:${{github.run_id}}
            docker push ${{ secrets.DOCKER_USERNAME }}/bank-account:latest
